language: rust

rust:
    - nightly

cache:
    cargo: true

addons:
    apt:
        packages:
            - libgexiv2-dev

env:
    - RUST_TEST_THREADS=1

script:
    - cargo build
    - cargo test
